{% set version = "2.1.0" %}

package:
  name: wasmer
  version: {{ version }}

source:
  url: https://github.com/wasmerio/wasmer/archive/{{ version }}.tar.gz
  sha256: 3d2d15bce1fc571f498000dcdab01695cc2a7994dbb9e8815d31ac21dda94fe3

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
    - llvmdev >=11
  host:
    - libffi
    - openssl
    - zlib
  run: []

# TODO: Also Included in the 1.0.1 release is an experimental, minified version
#       of wasmer called wasmer-headless that can only run precompiled Wasm modules.
# outputs:

# TODO: ideally have some "canonical" WASM to run...
{% set test_wasm = "tests/wasi-wast/wasi/snapshot1/hello.wasm" %}
{% set test_text = "Hello, world!" %}

test:
  source_files:
    - {{ test_wasm }}
  files:
    # TODO: we should probably generalize and package this as e.g.
    #       pytest-(conda-)cargo-liceneses, once we get cargo-licenses built
    - test_licenses.py
  requires:
    - m2-grep  # [win]
  commands:
    - wasmer --version
    - wasmer --help
    # TODO: remove jinja templates
    - wasmer validate {{ test_wasm }}
    - wasmer run {{ test_wasm }}
    - wasmer run {{ test_wasm }} | grep '{{ test_text }}'
    # TODO: enable C API, multiple outputs, use python testing infra, etc.
    # - mkdir .wsmr
    # {% for backend in ["singlepass", "cranelift", "llvm"] %}
    # - wasmer run --{{ backend }} {{ test_wasm }}
    # - wasmer run --{{ backend }} {{ test_wasm }} | grep '{{ test_text }}'
    # - WASMER_DIR=$PREFIX wasmer create-exe --{{ backend }} {{ test_wasm }} -o ./hello-{{ backend }}
    # - ls -lathr hello-{{ backend }}
    # - ./hello-{{ backend }}
    # - ./hello-{{ backend }} | grep '{{ test_text }}'
    # {% endfor %}

about:
  home: https://wasmer.io
  license: MIT
  license_family: MIT
  summary: Universal WebAssembly runtime
  description: |
    Wasmer is a standalone JIT WebAssembly runtime, aiming to be fully
    compatible with WASI and Emscripten.
  dev_url: https://github.com/wasmerio/wasmer
  doc_url: https://docs.wasmer.io
  doc_source_url: https://github.com/wasmerio/docs.wasmer.io
  license_file:
    - LICENSE
    - ATTRIBUTIONS.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - bollwyvl
    - wolfv
